Code refactoring and adding extra logic for avoiding obstacles
alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat pull request #9
Opened 2024-10-08 11:59 UTC by OctavianVladutAltom

- add new logic for avoiding obstacles
- adding extra logic for performing jump/slide/move left & right by using the swiping mechanism
- refactor existing code by:
  - extracting element identifiers
  - extracting and generalizing altFind and altWait parameters
  - extracting logic from test classes

2025-04-10 14:28 UTC, levibalint requested changes

2025-04-10 14:28 UTC, levibalint commented on src/test/java/GamePlayTest.java
>          System.out.println("Current life after avoiding obstacles: " + gamePlayPage.getCurrentLife());
In order to avoid false positives, I would recommend creating a variable to store `gamePlayPage.getCurrentLife()` right at the end, since re-running this a couple of times, I got Fails due to the cat dying right after exiting `gamePlayPage.avoidObstacles(5);`

2025-04-10 14:28 UTC, levibalint commented on src/test/java/GamePlayTest.java
> +        System.out.println("Current life after the preset number of seconds: " + gamePlayPage.getCurrentLife());
same as above, there is a risk that the cat will die after exiting `gamePlayPage.surviveTimeByAvoidingObstacles(20);`

2025-04-10 14:28 UTC, levibalint commented on src/main/java/pages/GamePlayPage.java
> +    public int getDistanceCovered(GetAnotherChancePage getAnotherChancePage) throws Exception {
I would recommend changing this a little bit to only return Math.round(zDistance) (i.e. the calculated distance covered).

While in `testDistanceRun()`'s [assert](https://github.com/alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat/pull/9/files#diff-feccbb9fd9b2c669511f54d3804b755b3ec38b3aa9cc7e92947931bbc0a23cd7R98) compare the returned value with `gamePlayPage.getDistanceRun();` instead of comparing the difference between the two numbers to 0

2025-04-10 14:28 UTC, levibalint commented on src/main/java/pages/GamePlayPage.java
> +            removeObstaclesBehindCharacter(allObstacles, character1);
I'm not sure if this change is equivalent with the original. Before, the objects in toBeRemoved are removed from allObstacles ([here](https://github.com/alttester/EXAMPLES-Java-Standalone-and-Android-AltTrashCat/pull/9/files#diff-0c1ceba4493a34a0488f83157b535423d08b1cec8bf5188f5b9c544d09a82657L81)), but removeObstaclesBehindCharacter() doesn't do that implicitly (just returns the number of obstacles).

Am I missing something? 🤔

2025-04-10 14:28 UTC, levibalint commented on src/main/java/pages/GamePlayPage.java
> +            counterObstaclesPassed += removeObstaclesBehindCharacter(allObstacles, character1);
From what I can tell, this counter is called way on a way higher frequency than expected, so when this value is printed, the value is unreasonably high (e.g. `94 obstacles passed`)

Wondering if there's a way to make sure that we only count an obstacle 1x after the cat passed them

I know that `testCollectFishBonesOnMiddleLane()` accounts for passed fish with a tolerance. Maybe the same should be applied here?

2025-04-10 14:28 UTC, levibalint commented on src/main/java/pages/GamePlayPage.java
> +    public void surviveTimeByAvoidingObstacles(long seconds) {
Since there is now an `avoidObstacles()` method and a `surviveTimeByAvoidingObstacles()` method in `GamePlayPage`,  I wonder if it's worth creating a (more) generic method of avoiding obstacles which would take a stopping mechanism as a parameter.

We could then have more specific methods that would call this generic method with either the number of obstacles OR number of seconds as the stopping mechanism.

2025-04-29 10:41 UTC, levibalint commented on src/test/java/GamePlayTest.java
>          System.out.println("Current life after avoiding obstacles: " + gamePlayPage.getCurrentLife());
fixed!

2025-04-29 10:42 UTC, levibalint commented on src/main/java/pages/GamePlayPage.java
> +    public int getDistanceCovered(GetAnotherChancePage getAnotherChancePage) throws Exception {
fixed

2025-05-05 14:55 UTC, RobertPoienar approved these changes

2025-05-08 07:36 UTC, levibalint approved these changes

2025-05-08 07:40 UTC, merged